### ISSUE TITLE
[Engine]: Editing hidden widgets

### ISSUE THREAD

**Issue by cuvar** [cuvar/panal#96]
**Problem**
Widgets can be hidden on various screens. Hence, they cannot be edited or added when "edit layout". This makes it hard to edit them or add them

**Solution**
- Maybe introduce a view with all current widgets > listview
- show a list of __hidden widgets__ that can be added for layout

**Todo**
- [x] basic sideview with list of hidden widgets
- [x] when adding a widget from sideview, there is a bug --> reproduce: add widget and then DO NOT press save!
- [x] better UI for sideview --> also for mobile --> maybe hamburger menu on left?
- [x] Add `eyeIcon` to widgets in layout editor -> easy way of hiding them
- [ ] write tests
